export const metalOptions = [
  { label: 'кабеля', price: 750 },
  { label: 'меди', price: 800 },
  { label: 'латуни', price: 480 },
  { label: 'бронзы', price: 500 },
  { label: 'алюминия', price: 190 },
  { label: 'нержавейки 10%', price: 290 },
  { label: 'титана', price: 2400 },
  { label: 'олова', price: 2400 },
  { label: 'поса', price: 2300 },
  { label: 'свинца', price: 120 },
  { label: 'аккумуляторов', price: 65 },
  { label: 'быстрореза', price: 1200 },
  { label: 'нихрома', price: 1000 },
  { label: 'тантала', price: 18000 },
  { label: 'молибдена', price: 3750 },
  { label: 'вк/тк', price: 1750 },
  { label: 'ниобия', price: 3800 },
  { label: 'кобальта', price: 1650 },
  { label: 'висмута', price: 450 },
  { label: 'бабита', price: 1900 },
];
